### ISSUE TITLE
MSpawns v2.0 To-Do

### ISSUE THREAD

**Issue by Flavius12** [EvolSoft/MSpawns#5]
MSpawns v2.0 upcoming features:
- [x] Fix teleport on join bug (maybe related to PocketMine)
- [x] Fix force hub
- [x] Fix spawn messages for hubs
- [x] Fix teleport on death
- [x] Add multi server support

**Comment by Flavius12** [comment]
Done! :smile:
